### ISSUE TITLE
Installation problem on OSX

### ISSUE THREAD

**Issue by rougier** [mir-am/LightTwinSVM#3]
I tried to run the `setup.sh` on OSX (10.14.2) using `Python 3.7.2`  but the script failed without much information. Is there a way to have more debug information?

```
The Installation of LightTwinSVM program:
Make sure that you are connected to the internet so that dependencies can be downloaded.
Press enter to start the installation process...
***************************************
Step 1:
Python 3.5 or newer detected on your system...
pip tool is detected...
***************************************
Step 2:
Installs required Python packages to run the program...
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 2)) (1.15.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 3)) (1.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 4)) (0.19.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 5)) (0.23.4)
Collecting pybind11 (from -r requirments.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/f2/7c/e71995e59e108799800cb0fce6c4b4927914d7eada0723dd20bae3b51786/pybind11-2.2.4-py2.py3-none-any.whl (145kB)
    100% |████████████████████████████████| 153kB 4.8MB/s
Collecting xlsxwriter (from -r requirments.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/8d/d0/f4ee9c621902d18807dd88b0a0ff4426666af8dd1e952c4943a9415f3eeb/XlsxWriter-1.1.4-py2.py3-none-any.whl (142kB)
    100% |████████████████████████████████| 143kB 5.3MB/s
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 9)) (0.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.7/site-packages (from pandas->-r requirments.txt (line 5)) (2018.5)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.7/site-packages (from pandas->-r requirments.txt (line 5)) (2.7.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas->-r requirments.txt (line 5)) (1.11.0)
Installing collected packages: pybind11, xlsxwriter
Successfully installed pybind11-2.2.4 xlsxwriter-1.1.4
Checks existence of Python's Tkinter...
Found python3-tk on your system...
Looking for Python 3 dev. package...
Found Python 3 dev on your system...
***************************************

Step 3:
Checks existence of LAPACK and BLAS...
Cloning into 'temp'...
remote: Enumerating objects: 1, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 4513 (delta 0), reused 0 (delta 0), pack-reused 4512
Receiving objects: 100% (4513/4513), 8.44 MiB | 7.95 MiB/s, done.
Resolving deltas: 100% (2920/2920), done.
The C++ extension moudle is generated...
***************************************

The installation failed... Number of compeleted steps: 6
```

**Comment by mir-am** [comment]
Hi

Thank you for reviewing the LightTwinSVM program.
Based on the above output, the installation is almost completed. Looks like the last step failed which is compiling the C++ extension module (optimizer).
My first guess is that the setup script fails to detect your OSX system. Therefore, the C++ extension cannot be generated.
I think $OSTYPE variable is different on your OSX system from what is hard-coded in the setup script.
Anyhow, I have added more debug information to setup.sh file so that we can fix the installation issue on your system.
Please run the setup.sh file again and copy-paste the output of setup script here.

Regards,
Mir

**Comment by rougier** [comment]
I've update my copy, but still the same cryptic final message. Is there an option for setup debug?

```
The Installation of LightTwinSVM program:
Make sure that you are connected to the internet so that dependencies can be downloaded.
Press enter to start the installation process...
***************************************
Step 1:
Python 3.5 or newer detected on your system...
Python version: Python 3.7.2
OS: darwin18
pip tool is detected...
***************************************
Step 2:
Installs required Python packages to run the program...
Requirement already satisfied: numpy in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 2)) (1.15.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 3)) (1.1.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 4)) (0.19.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 5)) (0.23.4)
Requirement already satisfied: pybind11 in /Users/rougier/Library/Python/3.7/lib/python/site-packages (from -r requirments.txt (line 6)) (2.2.4)
Requirement already satisfied: xlsxwriter in /Users/rougier/Library/Python/3.7/lib/python/site-packages (from -r requirments.txt (line 7)) (1.1.4)
Requirement already satisfied: sklearn in /usr/local/lib/python3.7/site-packages (from -r requirments.txt (line 9)) (0.0)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python3.7/site-packages (from pandas->-r requirments.txt (line 5)) (2018.5)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.7/site-packages (from pandas->-r requirments.txt (line 5)) (2.7.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil>=2.5.0->pandas->-r requirments.txt (line 5)) (1.11.0)
Checks existence of Python's Tkinter...
Found python3-tk on your system...
Looking for Python 3 dev. package...
Found Python 3 dev on your system...
***************************************

Step 3:
Checks existence of LAPACK and BLAS...
Found Armadillo repository. No need to clone again.
Failed to generate the C++ extension module...
***************************************

The installation failed... Number of steps completed: 5
```

**Comment by mir-am** [comment]
For now, a step-by-step guide is provided [here](https://github.com/mir-am/LightTwinSVM/wiki/Building-the-LightTwinSVM-manually-on-Linux-and-OSX-systems) to build the program manually.

Also, I try to fix the setup script for OSX systems. Based on the above output, there is a problem in conditions of if statements in the bash script.

https://github.com/mir-am/LightTwinSVM/blob/e820dde718c9675bcf7279e0bf537cc2acfc76f4/setup.sh#L183

Of course, a simple solution would be creating a separate shell script for OSX systems. However, there are some shared installation steps for both OSX and Linux systems, which I think it is better to have one setup script for both systems.

**Comment by rougier** [comment]
Now I get 
```
 $  g++ -O3 -Wall -shared -std=c++11 -fPIC `python3 -m pybind11 --includes` ./ltsvm/optimizer/pybind_clippdcd.cpp -o ./ltsvm/optimizer/clipdcd`python3-config --extension-suffix` -I ./temp/include -DARMA_DONT_USE_WRAPPER -framework Accelerate
/anaconda3/bin/python3: No module named pybind11
./ltsvm/optimizer/pybind_clippdcd.cpp:27:10: fatal error: 'pybind11/pybind11.h' file not found
#include <pybind11/pybind11.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by rougier** [comment]
After having installed pybind11 via Homebrew, compilation still doesn't work because of a missing Python.h (that is installed). I suspect the unusual command line might be the cause

**Comment by mir-am** [comment]
> After having installed pybind11 (via Homebrew), compilation still doesn't work with a lot of undefined symbols that seem to indicate some base libraries (Python) are not compatible. Do you have an alternative way to install it?

pybind11 is included in the "requirements.txt" file, which will be installed by pip. Anyhow, I fixed compilation error for OSX. A different compiler flag should have added to g++ command for OSX, which solves the linking error (undefined symbols).
Please compile the C++ extension using the following command:

``` 
g++ -O3 -Wall -shared -std=c++11 -undefined dynamic_lookup `python3 -m pybind11 --includes` ./ltsvm/optimizer/pybind_clippdcd.cpp -o ./ltsvm/optimizer/clipdcd`python3-config --extension-suffix` -I ./temp/include -DARMA_DONT_USE_WRAPPER -framework Accelerate
``` 

I have tested the above command and it successfully compiles the extenstion module on OSX machine of Travis CI.

If you received another error during installation, please let me know.

**Comment by rougier** [comment]
I managed to compile using your line but the setup.sh is still broken.

**Comment by rougier** [comment]
Any idea ?

**Comment by mir-am** [comment]
> Any idea ?

Unfortunately, I don't have access to Mac OSX system to test the setup script and then fix it. However, I might be able to solve the issue using Travis CI's OSX machines. Therefore, it may take several days.

To speed up the review process, please follow the [step-by-step guide](https://github.com/mir-am/LightTwinSVM/wiki/Building-the-LightTwinSVM-manually-on-Linux-and-OSX-systems) to test and review the LightTwinSVM program.

After all, I will fix this issue as soon as possible.

**Comment by rougier** [comment]
The last release seems to be working, at least for the manual instruction. `setup.sh` still fails but I imagine it is now easier to fix. Test also passed. I'm closing the issue.

**Comment by mir-am** [comment]
@rougier 
I managed to fix the setup.sh issue on Travis CI's virtual OSX system. The issue was somehow a hidden syntax problem!
I appreciate if you clone the repo again and run the setup.sh script. Thanks.

**Comment by rougier** [comment]
Just did it and it works now.
